### ISSUE TITLE
Discussion on #Topics/Grid/MasterDetail/Grid-And-Detail-View

### ISSUE THREAD

**Issue by thekingofspain** [GrapeCity/wijmo-doc#7]
Can you please include a running example of this code on the page or provide a link to the running example.

---
#### Topics/Grid/MasterDetail/Grid-And-Detail-View

**Comment by banzor** [comment]
Hey, we have a few examples that might be interesting to you. The code is in the example pages. 

1. [https://www.grapecity.com/wijmo/demos/Grid/Master-Detail/NestedGrids(RowDetail)/purejs](https://www.grapecity.com/wijmo/demos/Grid/Master-Detail/NestedGrids(RowDetail)/purejs) - showing master/detail in nested grids
2. [https://www.grapecity.com/wijmo/demos/Grid/Master-Detail/SeparateGrids/purejs](https://www.grapecity.com/wijmo/demos/Grid/Master-Detail/SeparateGrids/purejs) - showing master/detail in separate grids

**Comment by thekingofspain** [comment]
Thanks for the references.  But my orginal questons still reamins.   What is the syntax needed to set the
childItemsPath or binding  propery value to point to a specific object sequent and property of the data structure?

From the documentation, childItemsPath only mentions its used for identifying an object name that should be used as a child row.  I was hoping the property would support a namespace child definition such that the c in a.b.c could be selected while skipping over the a.c object as its not desired, but it soulnds like both c's or nothing.  I can live with that.

So in this mode we define a set of columns, and if a data item property name matches the binding name of a column, the data item's value is dislayed in the cell for that column and row.  Is it possible to do this on a data structure with a common concept of having a namish field defined at each level, but at each level's namish field is called something different?

"data": [
            {"MainId": 1111,  "firstName": "Sherlock",    "lastName": "Homes",  "categories": [
                        {  "CategoryID": 1, "CategoryName": "Example" }
                  ]
            }
        ]

________________________________

**Comment by banzor** [comment]
It is not possible to pass something like "b.c" into the childItemsPath. You can make a property that just returns it though. For example, you could add a d property that just returns "b.c". 

Regarding namish fields, they really need to match. The grid needs a common field in the column to bind to (if you want data to be displayed in the column that has the expand/collapse arrow. 

Alternatively, you can include multiple name columns that reference their specific binding. Then the grid will only render data in them when it exists at that level. I am not sure this is a good solution, but here is an example: [https://jscodemine.grapecity.com/share/WL3cUk4diUWiU1hs7Njh4g/?defaultOpen=%7B%22OpenedFileName%22%3A%5B%22%2Findex.html%22%5D%2C%22ActiveFile%22%3A%22%2Findex.html%22%7D](https://jscodemine.grapecity.com/share/WL3cUk4diUWiU1hs7Njh4g/?defaultOpen=%7B%22OpenedFileName%22%3A%5B%22%2Findex.html%22%5D%2C%22ActiveFile%22%3A%22%2Findex.html%22%7D)

This also shows how to bind to different structures of data at different levels.

**Comment by thekingofspain** [comment]
Sorry, I owe everyone an apology.

I thought the email response i received was to a question I asked on the wijmo fourm, not the comment I posted on github.  I did not realize this was not case until some responded to my question on the forum and I did not see your reply on the forum.  Then it clicked.

Thank again for the links to the examples.

erik
________________________________
