### ISSUE TITLE
Discussion on #/wijmo/docs/Topics/Grid/Rows/Adding-and-Removing-Rows

### ISSUE THREAD

**Issue by akshayrajput7195** [GrapeCity/wijmo-doc#9]
Incorrect mention of API: https://developer.mescius.com/wijmo/docs/Topics/Grid/Rows/Adding-and-Removing-Rows#:~:text=new%20row%20template.-,allowRemove,-%3A%20Setting%20this%20property

current description says 'allowRemove'

correction: instead of 'allowRemove' use: 'allowDelete'

reference: https://developer.mescius.com/wijmo/api/classes/Wijmo_Grid.Flexgrid.html#allowwbrdelete
---
#### /wijmo/docs/Topics/Grid/Rows/Adding-and-Removing-Rows

**Comment by banzor** [comment]
Thank you so much for reporting this! It is now fixed.
